[package]
name = "g-mind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", brach = "master" }

[lib]
crate-type = ["cdylib"]
